import type { Group, Member } from "@/lib/types";

export const sampleGroups: Group[] = [
  { id: "g-faith-1", name: "믿음 1", leaderMemberId: "m-2", leaderName: "박서준" },
  { id: "g-hope-2", name: "소망 2", leaderMemberId: "m-3", leaderName: "이예린" },
  { id: "g-love-3", name: "사랑 3", leaderMemberId: "m-4", leaderName: "최도윤" },
  { id: "g-young-a", name: "청년부 A", leaderMemberId: "m-5", leaderName: "정민재" },
  { id: "g-new", name: "새가족", leaderMemberId: "m-6", leaderName: "한지우" },
];

export const sampleMembers: Member[] = [
  {
    authUserId: null,
    id: "m-1",
    name: "김하은",
    phone: "010-2145-7301",
    groupId: "g-faith-1",
    groupName: "믿음 1",
    role: "leader",
    status: "active",
    email: "haeun.kim@example.com",
    address: "서울시 마포구",
    baptismStatus: "세례",
    notes: "다음 달 소그룹 리더 훈련 참석 예정",
    customFields: {},
    present: true,
    attendanceHistory: [],
    careFollowups: [],
  },
  {
    authUserId: null,
    id: "m-2",
    name: "박서준",
    phone: "010-7712-1185",
    groupId: "g-faith-1",
    groupName: "믿음 1",
    role: "leader",
    status: "active",
    email: "seojoon.park@example.com",
    address: "서울시 서대문구",
    baptismStatus: "입교",
    notes: "주중 심방 가능",
    customFields: {},
    present: true,
    attendanceHistory: [],
    careFollowups: [],
  },
  {
    authUserId: null,
    id: "m-3",
    name: "이예린",
    phone: "010-9038-4521",
    groupId: "g-hope-2",
    groupName: "소망 2",
    role: "staff",
    status: "active",
    email: "yerin.lee@example.com",
    address: "경기도 고양시",
    baptismStatus: "세례",
    notes: "찬양팀 섬김",
    customFields: {},
    present: false,
    attendanceHistory: [],
    careFollowups: [],
  },
  {
    authUserId: null,
    id: "m-4",
    name: "최도윤",
    phone: "010-5820-3904",
    groupId: "g-love-3",
    groupName: "사랑 3",
    role: "leader",
    status: "care",
    email: "doyoon.choi@example.com",
    address: "서울시 은평구",
    baptismStatus: "미확인",
    notes: "최근 3주 결석. 리더가 연락 예정",
    customFields: {},
    present: false,
    attendanceHistory: [],
    careFollowups: [],
  },
  {
    authUserId: null,
    id: "m-5",
    name: "정민재",
    phone: "010-4482-9300",
    groupId: "g-young-a",
    groupName: "청년부 A",
    role: "admin",
    status: "active",
    email: "minjae.jung@example.com",
    address: "서울시 용산구",
    baptismStatus: "세례",
    notes: "전체 운영 담당",
    customFields: {},
    present: true,
    attendanceHistory: [],
    careFollowups: [],
  },
  {
    authUserId: null,
    id: "m-6",
    name: "한지우",
    phone: "010-6304-8712",
    groupId: "g-new",
    groupName: "새가족",
    role: "leader",
    status: "new",
    email: "jiwoo.han@example.com",
    address: "서울시 강서구",
    baptismStatus: "미정",
    notes: "새가족 4주 과정 2주차",
    customFields: {},
    present: true,
    attendanceHistory: [],
    careFollowups: [],
  },
  {
    authUserId: null,
    id: "m-7",
    name: "윤서아",
    phone: "010-3290-7744",
    groupId: "g-hope-2",
    groupName: "소망 2",
    role: "member",
    status: "active",
    email: "seoa.yoon@example.com",
    address: "서울시 중구",
    baptismStatus: "세례",
    notes: "소그룹 회계 섬김",
    customFields: {},
    present: true,
    attendanceHistory: [],
    careFollowups: [],
  },
  {
    authUserId: null,
    id: "m-8",
    name: "오준호",
    phone: "010-8122-6509",
    groupId: "g-love-3",
    groupName: "사랑 3",
    role: "member",
    status: "care",
    email: "junho.oh@example.com",
    address: "경기도 부천시",
    baptismStatus: "미확인",
    notes: "개인 일정으로 예배 참석 불규칙",
    customFields: {},
    present: false,
    attendanceHistory: [],
    careFollowups: [],
  },
];
